# Generated by Django 3.2 on 2021-04-13 07:34

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210412_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[500, 300], upload_to='products/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
